routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\DB;
use App\Trip;

Route::get('/', function () {
    return view('welcome');
});

//route untuk form 
Route::get('/register', 'AuthController@getRegister')->name('register')->middleware('guest');
Route::post('/register', 'AuthController@postRegister')->middleware('guest');
Route::get('/login', 'AuthController@getLogin')->name('login')->middleware('guest');
Route::post('/login', 'AuthController@postLogin')->middleware('guest');
Route::get('/logout','AuthController@logout')->middleware('auth')->name('logout');
//end form
Route::get('/home','AuthController@index')->name('pages.home')->middleware('auth'); ;
Route::get('/tbl_employee','EmployeeController@index')->name('pages.form.employee')->middleware('auth'); ;
Route::get('/personalcarusage', function () { return view('pages.personal');})->middleware('auth'); ; 
//clue form 

Route::get('/cluepersonal', function () { return view('pages.clue.cluepersonal');})->middleware('auth'); 
Route::get('/changepersonal', 'testingApiController@getdata')->name('change.personal');

//form input
Route::get('/formpersonal', 'PersonalController@index')->name('pages.form.personal')->middleware('auth');
Route::post('/formpersonal', 'PersonalController@store')->name('pages.form.personal')->middleware('auth');  
Route::get('/viewpersonal', 'PersonalController@getview')->name('pages.tbl_personal')->middleware('auth');
Route::get('/submissionform', 'SubmissionFormController@index')->name('pages.commutersubmissionform')->middleware('auth');
Route::get('/formemployee','EmployeeController@create')->name('pages.form.employee')->middleware('auth'); 
Route::post('/formemployee','EmployeeController@store')->name('pages.form.employee')->middleware('auth'); 
Route::get('/recruitment', 'RecruitmentController@create')->name('pages.recruitment')->middleware('auth');
Route::get('get-bank-list','RecruitmentController@getBankList')->middleware('auth');
Route::get('get-branch-list','RecruitmentController@getBranchList')->middleware('auth');
Route::post('/recruitment','RecruitmentController@store')->name('pages.recruitment')->middleware('auth');
Route::get('/tablerecruitment','RecruitmentController@index')->name('pages.tbl_recruitment')->middleware('auth');
Route::get('/tablerecruitment/cetak_pdf', 'RecruitmentController@cetak_pdf')->middleware('auth');


Route::get('/bankcode','RecruitmentController@getbank')->name('bank')->middleware('auth');
Route::post('bankcode/fetch','RecruitmentController@fetch')->name('bank.fetch')->middleware('auth');


//export dan view form to csv
Route::get('/viewpersonal/export_excel', 'PersonalController@exportcsv')->name('export_excel.excel')->middleware('auth');
Route::get('/tablerecruitment/cetak_csv', 'RecruitmentController@exportcsv')->name('export_excel.excel')->middleware('auth');





Route::resource('/testingform','testingApiController')->middleware('auth');

//Route::get('/testingform', 'SubmissionFormController@create')->name('pages.testing');
Route::get('/table/user', 'TestingApiController@dataTable')->name('table.user')->middleware('auth');

Route::post('testingform/uploud','testingApiController@uploudfile')->name('testing.uploud')->middleware('auth');


Route::get('/table/user', 'TestingApiController@dataTable')->name('table.user')->middleware('auth');
Route::get('add-to-log', 'HomeController@myTestAddToLog');
Route::get('logActivity', 'HomeController@logActivity');

// Route::any('test', function(){
//     $trip = Trip::groupBy('user_id')
//             ->select('user_id', DB::raw('count(*) as total_trip'))
//             ->get();
    
    
//     return $trip;
// });

resources/views/pages/bank.blade.php
@extends('pages.home')
@section('content')

<h2 class="text-center">Employee Form</h2><br><br>


<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row ">
                <div class="col-6">
                             <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Horizontal Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal">
                  <div class="card-body">
                    <div class="form-group row">
                    <label>SELECT BANK</label>
                      <select name="bank_name" id="bank_name" class="form-control input-lg dynamic" data-dependent="branch_name">
                          <option>Select Bank</option>
                          @foreach ($bank_list as $bank_name)
                          <option value="{{$bank_name -> bank_name}}">{{$bank_name->bank_name}}</option>                             
                          @endforeach
                      </select>
                    </div>
                    <div class="form-group row">
                            <label>Branch Name</label>
                              <select name="bank_name" id="bank_name" class="form-control input-lg dynamic" data-dependent="bank_code">
                                  <option>Branch name</option>
                              
                              </select>
                    </div>
                   
                    <div class="form-group row">
                        <label>BANK CODE</label>
                            <select name="bank_name" id="bank_name" class="form-control input-lg dynamic" >
                                <option>Code Bank</option>
                             
                            </select>
                    </div>
                    {{ csrf_field()}}
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-info">Save</button>
                    <button type="submit" class="btn btn-default float-right">Cancel</button>
                  </div>
                  <!-- /.card-footer -->
                </form>
              </div>        
            </div>
            </div>
        </div>
    </div>
    
</div>

@endsection
<script type="text/javascript">
        var $ = jQuery;
        $(document).ready(function(){
        
         $('.dynamic').change(function(){
          if($(this).val() != '')
          {
           var select = $(this).attr("id_bank");
           var value = $(this).val();
           var dependent = $(this).data('dependent');
           var _token = $('input[name="_token"]').val();
           $.ajax({
            url:"{{ route('bank.fetch') }}",
            method:"POST",
            data:{select:select, value:value, _token:_token, dependent:dependent},
            success:function(result)
            {
             $('#'+dependent).html(result);
            }
        
           })
          }
         });
        
         $('#bank_name').change(function(){
          $('#branch_name').val('');
          $('#bank_code').val('');
         });
        
         $('#branch_name').change(function(){
          $('#bank_code').val('');
         });
         
        
        });
</script>

resources/views/pages/employee.blade.php
@extends('pages.home')
@section('content')

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<h2 class="text-center">Table Personal</h2>

<table>
  <tr>
    <th>Firstname</th>
    <th>Contact</th>
    <th>Approve</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
  <tr>  
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td><div class="col-sm-6">
          <input type="radio" name="gender" value="male"> Approve
          <input type="radio" name="gender" value="female"> Reject
    </div></td>
  </tr>
</table>

@endsection

resources/views/pages/formemployee.blade.php
@extends('pages.home')
@section('content')

<h2 class="text-center">Employee Form</h2><br><br>darr


<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row ">
                <div class="col-md-6">
                             <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Horizontal Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal">
                  <div class="card-body">
                    <div class="form-group row">
                      <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                      <div class="col-sm-10">
                        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <div class="form-check">
                          <input type="checkbox" class="form-check-input" id="exampleCheck2">
                          <label class="form-check-label" for="exampleCheck2">Remember me</label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-info">Sign in</button>
                    <button type="submit" class="btn btn-default float-right">Cancel</button>
                  </div>
                  <!-- /.card-footer -->
                </form>
              </div>


                
                
                    
            
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/recruitmen_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Membuat Laporan PDF Dengan DOMPDF Laravel</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<div class="text-center">
		<h5>Membuat Laporan PDF Dengan DOMPDF Laravel</h4>
		<h6><a target="_blank" href="https://www.hamton-solutions/">www.hamton-solutions.com</a></h5>
	</div>
 
	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Firstname</th>
				<th>Surname</th>
				<th>PhoneNumber</th>
			
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($recruitment as $recruit)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{$recruit->firstname_kanji}}</td>
				<td>{{$recruit->surname_kanji}}</td>
				<td>{{$recruit->phone_number}}</td>				
			</tr>
			@endforeach
		</tbody>
	</table>
 
</body>
</html>

resources/views/pages/tbl_employee.blade.php
@extends('pages.home')
@section('content')

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<h2 class="text-center"> Employee Table</h2>
<div class="container">
  <div class="card">
    <div class="card-header">
            Featured
            <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 300px, height: 500px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
          </div>
        </div>
    </div>
    <div class="card-body table-responsive p-0" style="height: 500px;">
            <table class="table table-head-fixed">
              <thead>
                <tr>
                  <th>No数</th>
                  <th>First Name</th>
                  <th>Surname</th>            
                  <th>Dormitory</th>                        
                  <th>Postal Code </th>
                  <th>Actionアクション</th>

                </tr>
              </thead>
              <tbody>
                    
                @foreach ($employee as $index=>$employees)                
                    <tr>
                        @if(isset($_GET['page']))               
                            <td>{{(5*($_GET['page']-1))+$index+1}}</td>
                        @else
                            <td>{{$index+1}}</td>
                        @endif
                        <td>{{$employees->firstname}}</td>
                        <td>{{$employees->surname}}</td>   
                        <td>{{$employees->dormitory_status}}</td>   
                        <td>{{$employees->postal_code}}</td>                                      
                        <td>
                            <a href="/edit/{{$employees->id_personal_usage}}" class="btn btn-success">Accepted</a>&nbsp;
                            <a href="/delete/{{ $employees->id_personal_usage }}"class="btn btn-danger">Rejected</a>                           
                        </td>                                      

                    </tr> 
                @endforeach
                </tbody>
            </table>
    </div>
</div>

@endsection

resources/views/pages/tbl_personal.blade.php
@extends('pages.home')
@section('content')

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<h2 class="text-center"> Personal Table</h2>

<div class="container">
  <div class="card">
    <div class="card-header">         
            <a href="{{route('export_excel.excel')}}" class="btn btn-primary" target="_blank">Export Csv</a>
            
            <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 300px, height: 500px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
          </div>
        </div>
    </div>

    <div class="card-body table-responsive p-0" style="height: 500px;">
        <table class="table table-head-fixed">
          <thead>
            <tr>
              <th>No数</th>
              <th>Store number Code</th>
              <th>Employee Number</th>            
              <th>FullName</th>                        
              <th>Currently Month Enter </th>
              <th>Actionアクション</th>

            </tr>
          </thead>
          <tbody>
                
            @foreach ($personal_usage as $index=>$personals)                
                <tr>
                    @if(isset($_GET['page']))               
                        <td>{{(5*($_GET['page']-1))+$index+1}}</td>
                    @else
                        <td>{{$index+1}}</td>
                    @endif
                    <td>{{$personals->store_number}}</td>
                    <td>{{$personals->employee_number}}</td>   
                    <td>{{$personals->fullname}}</td>   
                    <td>{{$personals->created_at}}</td>                                      
                    <td>
                        <a href="/edit/{{$personals->id_personal_usage}}" class="btn btn-success">Accepted</a>&nbsp;
                        <a href="/delete/{{ $personals->id_personal_usage }}"class="btn btn-danger">Rejected</a>
                        
                    </td>                                      

                </tr> 
            @endforeach
            </tbody>
        </table>









  </div>
</div>
@endsection

resources/views/pages/testingsubmission.blade.php
@extends('pages.home')
@section('content')

<style>
html, body {
  height: 100%;
}

.wrap {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.button {
  width: 140px;
  height: 45px;
  font-family: 'Roboto', sans-serif;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2.5px;
  font-weight: 500;
  color: #ffff;
  background-color: #ef4023;
  border: none;
  border-radius: 45px;
  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease 0s;
  cursor: pointer;
  outline: none;
  }

.button:hover {
  background-color:#acacac;
  box-shadow: 0px 15px 20px rgba(0, 0, 0, 0.0));
  color: #ffff;

}
.nav-first.row {
    margin-top: -20px;
}
hr.nav-second {
    margin-bottom: 0px;
    margin-top: 0px;
}

label {
   font-size: 12px;
   margin-left:10px
}
p {
   font-size: 14px;
}
.wrap.center {
    margin-left: 460px;
    margin-bottom: 10px;
}

.hidden{
    display:none;
}
.example{
    float: right;
    margin-top : -30px;
}
{
  box-sizing: border-box;
}

body {
  background-color: #f1f1f1;
}

#regForm {
  background-color: #ffffff;
  margin: auto;
  font-family: Raleway;
  padding: 40px;
  width: 70%;
  min-width: 300px;
}

h1 {
  text-align: center;  
}

input {
  padding: 10px;
  width: 100%;
  font-size: 17px;
  font-family: Raleway;
  border: 1px solid #aaaaaa;
}

/* Mark input boxes that gets an error on validation: */
input.invalid {
  background-color: #ffdddd;
}

/* Hide all steps by default: */
.tab {
  display: none;
}

button {
  background-color: #4CAF50;
  color: #ffffff;
  border: none;
  padding: 10px 20px;
  font-size: 17px;
  font-family: Raleway;
  cursor: pointer;
}

button:hover {
  opacity: 0.8;
}

#prevBtn {
  background-color: #bbbbbb;
}

/* Make circles that indicate the steps of the form: */
.step {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbbbbb;
  border: none;  
  border-radius: 50%;
  display: inline-block;
  opacity: 0.5;
}

.step.active {
  opacity: 1;
}

/* Mark the steps that are finished and valid: */
.step.finish {
  background-color: #4CAF50;
}

</style>
    <div class="nav-first row">
      <div class="col-md-12 card ">
          <div class="card-body">
            <div class="col-md-12 inline" style="margin-top:10px; margin-bottom:-20px">
                 <div style="color:#ef4023; font-weight:bold; font-size:18px;">Commuter Submission Form </div>         
                    <form class="example" action="/action_page.php" >
                        <label>Store Number</label>
                        <input type="text" placeholder="Store Number" name="search2" style="border-radius:2px">
                        <button type="submit" style="color:#ef4023;"><i class="fa fa-search " style="color:#ef4023;"></i></button>
                        <label>Employee Number</label>
                        <input type="text" placeholder="Employee Number" name="search2">
                        <button type="submit"style="Backgound:#ef4023;"><i class="fa fa-search"style="color:#ef4023;"></i></button>
                    </form>
                 
            </div>     `                                        
          </div>
            <hr class="nav-second" size="30px"color ="#ef4023"/>
      </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">              
                <label style="font-size:16px;">Terusty Harumdani</label>
                <label style="font-size:12px;">Tel : 099709809809</label>
                <label style="font-size:12px;">Menara Mandiri Cohive Lantai 11</label>
                <label style="font-size:12px;">Jakarta Selatan</label>

               
                <form id="regForm" action="/action_page.php">
                    <h1>Register:</h1>
                    <!-- One "tab" for each step in the form: -->
                    <div class="tab">Name:
                        <p><input placeholder="First name..." oninput="this.className = ''" name="fname"></p>
                        <p><input placeholder="Last name..." oninput="this.className = ''" name="lname"></p>
                    </div>
                    <div class="tab">Contact Info:
                        <p><input placeholder="E-mail..." oninput="this.className = ''" name="email"></p>
                        <p><input placeholder="Phone..." oninput="this.className = ''" name="phone"></p>
                    </div>
                    <div class="tab">Birthday:
                        <p><input placeholder="dd" oninput="this.className = ''" name="dd"></p>
                        <p><input placeholder="mm" oninput="this.className = ''" name="nn"></p>
                        <p><input placeholder="yyyy" oninput="this.className = ''" name="yyyy"></p>
                    </div>
                    <div class="tab">Login Info:
                        <p><input placeholder="Username..." oninput="this.className = ''" name="uname"></p>
                        <p><input placeholder="Password..." oninput="this.className = ''" name="pword" type="password"></p>
                    </div>
                    <div style="overflow:auto;">
                        <div style="float:right;">
                        <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
                        <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
                        </div>
                    </div>
                    <!-- Circles which indicates the steps of the form: -->
                    <div style="text-align:center;margin-top:40px;">
                        <span class="step"></span>
                        <span class="step"></span>
                        <span class="step"></span>
                        <span class="step"></span>
                    </div>
                </form>
               .            
             
            
            

               

            
            </div>       
        </div>
    </div>
    
    

</div>
<div class="card card-primary">
                        <h3 class="text-center" style=" font-size:16px ; font-weight: bold; margin-top:10px">Detail Commuting Entry</h3>
                            <div class="card-header">
                                <label class="card-title">Datatable </label>
                                <a href="{{route('testingform.create')}}" class="btn btn-success  float-md-right modal-show" style="margin-top: -8px; font-size:14px " title="Create User"><i class="fas fa-plus"></i> Add New Commuting Trip</a>
                            </div>
                            <div class="card card-primary">
                                <table id="datatable" class="table table-hover" style="width:100%; font-size:12px ">
                                
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Route Profile</th>
                                            <th>Date</th>
                                            <th>Type</th>
                                            <th>Transport</th>
                                            <th>Attandence Code</th>
                                            <th>Route</th>
                                            <th>Approve</th>                                        
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    


                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Route Profile</th>
                                            <th>Date</th>
                                            <th>Type</th>
                                            <th>Transport</th>
                                            <th>Attandence Code</th>
                                            <th>Route</th>
                                            <th>Approve</th>  
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                
                                </table>
                            </div>
                    </div>

@endsection

@push('scripts')
  
    <script>
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{route('table.user') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id'},
                {data: 'route_profile', name: 'route_profile'},
                {data: 'date', name: 'date'},
                {data: 'type', name: 'type'},
                {data: 'transport', name: 'transport'},
                {data: 'path', name: 'path'},               
                {data: 'route', name: 'route'},
                {data: 'approve', name: 'approve'},              
                {data: 'action', name: 'action'}
            ]
        });
    </script>

    <script>
        function ShowHideShowInfo(){
           
            $("#car").addClass('hide');
            if(document.getElementById('shipsame').checked){
                document.getElementById('car').style.display='block'; 
            }else{
                document.getElementById('car').style.display='none';
            }
        }
    
    </script>
        <script>
        function ShowHideShowtrain(){
           
            if(document.getElementById('trainsir').checked){
               
                document.getElementById('train').style.display='block'; 
            }else{
                
                document.getElementById('train').style.display='none';
            }
        }
    
    </script>
    <script>
        var currentTab = 0; // Current tab is set to be the first tab (0)
        showTab(currentTab); // Display the current tab

        function showTab(n) {
        // This function will display the specified tab of the form...
        var x = document.getElementsByClassName("tab");
        x[n].style.display = "block";
        //... and fix the Previous/Next buttons:
        if (n == 0) {
            document.getElementById("prevBtn").style.display = "none";
        } else {
            document.getElementById("prevBtn").style.display = "inline";
        }
        if (n == (x.length - 1)) {
            document.getElementById("nextBtn").innerHTML = "Submit";
        } else {
            document.getElementById("nextBtn").innerHTML = "Next";
        }
        //... and run a function that will display the correct step indicator:
        fixStepIndicator(n)
        }

        function nextPrev(n) {
        // This function will figure out which tab to display
        var x = document.getElementsByClassName("tab");
        // Exit the function if any field in the current tab is invalid:
        if (n == 1 && !validateForm()) return false;
        // Hide the current tab:
        x[currentTab].style.display = "none";
        // Increase or decrease the current tab by 1:
        currentTab = currentTab + n;
        // if you have reached the end of the form...
        if (currentTab >= x.length) {
            // ... the form gets submitted:
            document.getElementById("regForm").submit();
            return false;
        }
        // Otherwise, display the correct tab:
        showTab(currentTab);
        }

        function validateForm() {
        // This function deals with validation of the form fields
        var x, y, i, valid = true;
        x = document.getElementsByClassName("tab");
        y = x[currentTab].getElementsByTagName("input");
        // A loop that checks every input field in the current tab:
        for (i = 0; i < y.length; i++) {
            // If a field is empty...
            if (y[i].value == "") {
            // add an "invalid" class to the field:
            y[i].className += " invalid";
            // and set the current valid status to false
            valid = false;
            }
        }
        // If the valid status is true, mark the step as finished and valid:
        if (valid) {
            document.getElementsByClassName("step")[currentTab].className += " finish";
        }
        return valid; // return the valid status
        }

        function fixStepIndicator(n) {
        // This function removes the "active" class of all steps...
        var i, x = document.getElementsByClassName("step");
        for (i = 0; i < x.length; i++) {
            x[i].className = x[i].className.replace(" active", "");
        }
        //... and adds the "active" class on the current step:
        x[n].className += " active";
        }
    </script>
   
@endpush